### ISSUE TITLE
Change log pleading ignorance, but it knows. 

### ISSUE THREAD

**Issue by amandabee** [ecprice/newsdiffs#36]
I'm getting "Alas! We don't seem to know anything about this article. Sorry! :(" on pages for an article that definitely has recorded changes. 

I'm not sure what information would be helpful for my own instance, but I have a local instance running, and at <http://127.0.0.1:8000/article-history/www.sfgate.com/bayarea/article/As-Napa-cheers-quake-recovery-some-question-6462726.php>  I'm seeing this: 

    Article Change Log
    http: //www.sfgate.com/bayarea/article/As-Napa-cheers-quake-recovery-some-question-6462726.php

    Alas! We don't seem to know anything about this article. Sorry! :(

But, if I come in through browse: <http://127.0.0.1:8000/diff/150/162/www.sfgate.com/bayarea/article/As-Napa-cheers-quake-recovery-some-question-6462726.php>  I definitely see changes that I can compare. 

I see the same thing happening to a URL that is tracked in my instance and on `newsdiffs.org`: <http://127.0.0.1:8000/article-history/www.washingtonpost.com/local/montgomery-county-housing-application-moves-online/2015/08/20/05d93a2a-468f-11e5-846d-02792f854297_story.html> gives the "Alas!" error, even though if I come in through browse I see the (relatively minor) changes. I'd love any help figuring out how I can troubleshoot this.

**Comment by ecprice** [comment]
I'm a bit confused by your example: if I go to newsdiffs.org and search for www.washingtonpost.com/local/montgomery-county-housing-application-moves-online/2015/08/20/05d93a2a-468f-11e5-846d-02792f854297_story.html
then I do find the article.

There are several possibilities for what the issue might be.  For example:
 - It probably doesn't realize that http:// and https:// go to the same site.
 - It's possible that it caches the results; some pages have a 30 minute cache.
 - Note that on /diff/x/y/long-url links, the long-url is just for human readability -- you can change it arbitrarily.  So perhaps the link is different.
 - Related to that, you seem to have a space between the http: and the // in your text.

You can also troubleshoot by looking at the database directly.  Do something like
newsdiffs/website$ python manage.py shell
[...]
>>> from frontend.models import *
>>> Article.objects.get(url='http://sfgate.com/blah-blah')
to see if the article is in the database.

**Comment by amandabee** [comment]
Actually ... I somehow introduced the space in `views.py` and that was the whole problem. 

Now I'm embarrassed. But thank you!
